# Site settings
title: Amir Khosravanizadeh
logo: https://www.linkedin.com/in/amir-khosravanizadeh-857a91237/?originalSubdomain=fr
author:
  name: Amir Khosravanizadeh
  email: youremail@domain.com
description: I am a physicist..


# Build settings
theme: minimal-mistakes-jekyll


